// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.793
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func Logos() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<section class=\"bg-white pt-7 pb-14\"><div class=\"container px-8 mx-auto sm:px-12 lg:px-20\"><h1 class=\"text-sm font-bold tracking-wide text-center text-gray-800 uppercase mb-7\">Trusted by top-leading companies.</h1><div class=\"flex grid items-center justify-center grid-cols-12 grid-cols-12 gap-y-8\"><div class=\"flex items-center justify-center col-span-6 sm:col-span-4 md:col-span-3 xl:col-span-2\"><img src=\"https://cdn.devdojo.com/tails/images/disney-plus.svg\" alt=\"Disney Plus\" class=\"block object-scale-down h-18s w-36a\"></div><div class=\"flex items-center justify-center col-span-6 sm:col-span-4 md:col-span-3 xl:col-span-2\"><img src=\"https://cdn.devdojo.com/tails/images/google.svg\" alt=\"Google\" class=\"block object-scale-down h-18s w-36\"></div><div class=\"flex items-center justify-center col-span-6 sm:col-span-4 md:col-span-3 xl:col-span-2\"><img src=\"https://cdn.devdojo.com/tails/images/hubspot.svg\" alt=\"Hubspot\" class=\"block object-scale-down h-18s w-36\"></div><div class=\"flex items-center justify-center col-span-6 sm:col-span-4 md:col-span-3 xl:col-span-2\"><img src=\"https://cdn.devdojo.com/tails/images/youtube.svg\" alt=\"Youtube\" class=\"block object-scale-down h-18s w-36\"></div><div class=\"flex items-center justify-center col-span-6 sm:col-span-4 md:col-span-6 xl:col-span-2\"><img src=\"https://cdn.devdojo.com/tails/images/slack.svg\" alt=\"Slack\" class=\"block object-scale-down h-18s w-36\"></div><div class=\"flex items-center justify-center col-span-6 sm:col-span-4 md:col-span-6 xl:col-span-2\"><img src=\"https://cdn.devdojo.com/tails/images/shopify.svg\" alt=\"Shopify\" class=\"block object-scale-down h-18s w-36\"></div></div></div></section>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
